# DataSource config
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=mysldb;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=Vidhan@123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
