eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false  #THIS IS THE SERVER IT WILL NOT REGISTER WITH CLIENT THAT ARE MICROSERVICES INSTEAD CLIENT WILL REGISTER WITH SERVER..
    fetch-registry: false
server:
  port: 8761