spring:
  application:
    name: POST-SERVICE
  datasource:
      url:  jdbc:mysql://localhost:3306/postdb
      username: root
      password: test
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MYSQL8Dialect
server:
  port: 8081   # now we will identify microservices with name of project and not with port number because it can change and name is fix

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true  #true because this is client and it will interact with server
    server-url:
      defaultZone: http://localhost:8761/eureka


management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always


resilience4j:
  circuitbreaker:
    instances:
      commentBreaker:
        registerHealthIndicator: true  # CHECKS HEALTH OF ALL MICROSERVICES ALL OVER THE APP..it will give status of even the db
        eventConsumerBufferSize: 10   #TOTAL HOW MANY CALLS WE CAN MAKE..
        failureRateThreshold: 50  #THIS IS 50 PERCENTAGE OF MINIMUM NUMBERS OF CALLS
        minimumNumberOfCalls: 5   # 50 PERCENTAGE OF MINIMUM NUMBERS OF CLASS TO REACH A THRESHOLD  CLOSED TO OPEN  TO CONVERT ANY REQUEST
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10  # ACTUATOR WILL HOLD THE DATA OF RECENT 10 REQUESTS.
        slidingWindowType: COUNT_BASED









